"""visit_status_log table

Revision ID: 35b19dc29dac
Revises: 3b2df745e6b6
Create Date: 2026-09-16 22:35:47.825040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '35b19dc29dac'
down_revision: Union[str, Sequence[str], None] = '3b2df745e6b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # visitstatus enum type already exists (created in ccfda6a62567 for visits.status);
    # create_type=False avoids a duplicate CREATE TYPE, matching 3b2df745e6b6's pattern.
    op.create_table('visit_status_log',
    sa.Column('visit_id', sa.UUID(), nullable=False),
    sa.Column('from_status', postgresql.ENUM('RECEIVED', 'DIAGNOSTICS', 'APPROVAL', 'IN_PROGRESS', 'WAITING_PARTS', 'READY', 'ISSUED', 'CANCELLED', name='visitstatus', create_type=False), nullable=True),
    sa.Column('to_status', postgresql.ENUM('RECEIVED', 'DIAGNOSTICS', 'APPROVAL', 'IN_PROGRESS', 'WAITING_PARTS', 'READY', 'ISSUED', 'CANCELLED', name='visitstatus', create_type=False), nullable=False),
    sa.Column('changed_by_user_id', sa.UUID(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visit_status_log')
    # ### end Alembic commands ###
