"""visit_work_items table

Revision ID: 3b2df745e6b6
Revises: ccfda6a62567
Create Date: 2026-09-16 22:18:24.047093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '3b2df745e6b6'
down_revision: Union[str, Sequence[str], None] = 'ccfda6a62567'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visit_work_items',
    sa.Column('visit_id', sa.UUID(), nullable=False),
    sa.Column('catalog_item_id', sa.UUID(), nullable=True),
    sa.Column('free_text_name', sa.String(length=255), nullable=True),
    sa.Column('category', postgresql.ENUM('DIAGNOSTICS', 'MAINTENANCE', 'BODY', 'ELECTRICAL', 'CHASSIS', 'OTHER', name='workcategory', create_type=False), nullable=False),
    sa.Column('norm_hours', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('NOT_READY', 'IN_PROGRESS', 'WAITING_PARTS', 'READY', name='workitemstatus'), nullable=False),
    sa.Column('assigned_mechanic_id', sa.UUID(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('is_extra_work', sa.Boolean(), nullable=False),
    sa.Column('approved_by_client', sa.Boolean(), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_via', sa.Enum('CRM_STATUS', 'BOT', name='approvedvia'), nullable=True),
    sa.Column('progress_photos', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_mechanic_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['catalog_item_id'], ['work_catalog.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visit_work_items')
    # ### end Alembic commands ###
    # workcategory is shared with work_catalog table (created in c89cf817acea) and is
    # intentionally not dropped here. workitemstatus/approvedvia are owned by this table.
    sa.Enum(name='workitemstatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='approvedvia').drop(op.get_bind(), checkfirst=True)
