"""clients table

Revision ID: 7556ec1e18a5
Revises: db301969d872
Create Date: 2026-09-15 22:49:42.511624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7556ec1e18a5'
down_revision: Union[str, Sequence[str], None] = 'db301969d872'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone_normalized', sa.String(length=16), nullable=False),
    sa.Column('phone_display', sa.String(length=32), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=True),
    sa.Column('telegram_username', sa.String(length=64), nullable=True),
    sa.Column('client_type', sa.Enum('INDIVIDUAL', 'LEGAL', name='clienttype'), nullable=False),
    sa.Column('legal_details', sa.JSON(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_phone_normalized'), 'clients', ['phone_normalized'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clients_phone_normalized'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
