"""consent_drafts and consents tables

Revision ID: b25405d2177b
Revises: db86d669174d
Create Date: 2026-09-18 13:23:29.488110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b25405d2177b'
down_revision: Union[str, Sequence[str], None] = 'db86d669174d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consent_drafts',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('converted_client_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['converted_client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consent_drafts_token'), 'consent_drafts', ['token'], unique=True)
    op.create_table('consents',
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('draft_id', sa.UUID(), nullable=True),
    sa.Column('consent_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consent_text_version', sa.String(length=32), nullable=False),
    sa.Column('consent_method', sa.Enum('QR_ONSITE', 'PAPER', 'TELEGRAM_BOT_START', 'EMAIL_CONFIRMATION', 'SMS_OTP', name='consentmethod'), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('telegram_id', sa.Integer(), nullable=True),
    sa.Column('verification_ref', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['draft_id'], ['consent_drafts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consents')
    op.drop_index(op.f('ix_consent_drafts_token'), table_name='consent_drafts')
    op.drop_table('consent_drafts')
    # ### end Alembic commands ###
