"""work_catalog table

Revision ID: c89cf817acea
Revises: 71dd6fd08d5b
Create Date: 2026-09-16 14:59:34.635154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c89cf817acea'
down_revision: Union[str, Sequence[str], None] = '71dd6fd08d5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_catalog',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('DIAGNOSTICS', 'MAINTENANCE', 'BODY', 'ELECTRICAL', 'CHASSIS', 'OTHER', name='workcategory'), nullable=False),
    sa.Column('default_norm_hours', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_catalog')
    # ### end Alembic commands ###
