"""visits table

Revision ID: ccfda6a62567
Revises: c89cf817acea
Create Date: 2026-09-16 15:06:59.820630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccfda6a62567'
down_revision: Union[str, Sequence[str], None] = 'c89cf817acea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visits',
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('planned_ready_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mileage_at_intake', sa.Integer(), nullable=False),
    sa.Column('mileage_manually_confirmed', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('RECEIVED', 'DIAGNOSTICS', 'APPROVAL', 'IN_PROGRESS', 'WAITING_PARTS', 'READY', 'ISSUED', 'CANCELLED', name='visitstatus'), nullable=False),
    sa.Column('assigned_master_id', sa.UUID(), nullable=False),
    sa.Column('complaint_text', sa.String(), nullable=True),
    sa.Column('intake_photos', sa.JSON(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cancelled_reason', sa.String(), nullable=True),
    sa.Column('document_url', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_master_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visits')
    # ### end Alembic commands ###
