"""visit_part_items table

Revision ID: db86d669174d
Revises: 35b19dc29dac
Create Date: 2026-09-16 22:46:10.055583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db86d669174d'
down_revision: Union[str, Sequence[str], None] = '35b19dc29dac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visit_part_items',
    sa.Column('visit_id', sa.UUID(), nullable=False),
    sa.Column('work_item_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('article_number', sa.String(length=64), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('availability_status', sa.Enum('IN_STOCK', 'ORDERED', 'PENDING', name='partavailability'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.ForeignKeyConstraint(['work_item_id'], ['visit_work_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visit_part_items')
    # ### end Alembic commands ###
    # partavailability is owned solely by this table; drop_table doesn't
    # cascade-drop the enum type, so remove it explicitly (same pattern as
    # workitemstatus/approvedvia in 3b2df745e6b6_visit_work_items_table.py).
    sa.Enum(name='partavailability').drop(op.get_bind(), checkfirst=True)
